name: Dump SHA-1
on: [push]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Dump SHA-1
        run: |
          cd android
          chmod +x gradlew
          ./gradlew signingReport
